name: MOD Standards Frontpage Pipeline
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev-sandbox
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      name: Prepare NPM CI
    - run: CI='' npm run build --if-present
      name: Build React App
    - uses: alphagov/paas-cf-github-action@main
      name: Deploy to Cloud Foundry
      env:
        CF_API: ${{ secrets.CF_API }}
        CF_ORG: ${{ secrets.CF_ORG }}
        CF_SPACE: ${{ secrets.CF_SPACE }}
        CF_USERNAME: ${{ secrets.CF_USER }}
        CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
      with:
        args: push --strategy rolling -f manifest.yml